### ISSUE TITLE
Find a tip "Failed to discover OP endpoint URL"

### ISSUE THREAD

**Issue by jackzuan** [fnyah/Steam-Login-Express#1]
Find a tip "Failed to discover OP endpoint URL", help,help!

**Comment by fnyah** [comment]
Do you have any more details about the issue?

**Comment by jackzuan** [comment]
![image](https://github.com/fnyah/Steam-Login-Express/assets/1006029/1f1c1016-eb82-467a-90d1-82db58da178a)
![image](https://github.com/fnyah/Steam-Login-Express/assets/1006029/e767961a-438c-4779-95bb-e7ccf39e5fca)
I can not run at local. Would you can run in localhost?
Thank you for your help.

**Comment by fnyah** [comment]
Hey Yang. Go ahead and re-clone the project and install the packages, it should be working now. And don't forget to add your steam API key on line 82 in app.js. You can find your key here: https://steamcommunity.com/dev/apikey Please let me know if you have any other issues.

**Comment by yangdezuan** [comment]
![image](https://github.com/fnyah/Steam-Login-Express/assets/1006029/1bf71e55-a4d1-41fb-9d57-8286724926b1)
![image](https://github.com/fnyah/Steam-Login-Express/assets/1006029/1a38d586-f00d-4943-87f5-865787b41637)
Hey [fnyah](https://github.com/fnyah). Thank you for your prompt reply. I have re-cloned the project and reinstalled your package according to your tip, but I still receive this message.  Hope your reply. thanks.

**Comment by yangdezuan** [comment]
returnURL: 'http://localhost/auth/steam/return',
realm: 'http://localhost/',
apiKey: '685780B99FE6BA22A7BF5F5A85BFBEF2' // Your steam api key goes here!
Can you run the above code normally?

**Comment by fnyah** [comment]
Hey Yang, I have deleted your previous post as it exposes your steam API key (you should keep that private). 
It looks like you're missing the port in your localhost URL. I recommend resetting your steam API key ASAP.

Try this: 
returnURL: 'http://localhost:3000/auth/steam/return',
realm: 'http://localhost:3000/',
apiKey: '' // Your steam api key goes here!

**Comment by fnyah** [comment]
I recommend resetting your steam API key ASAP.

**Comment by jackzuan** [comment]
Thank you for the kind reminder, but did I add port 3000, or is that still the case?
![image](https://github.com/fnyah/Steam-Login-Express/assets/1006029/f8238869-05ff-4f2d-8c46-36b2fd7e8074)
Are you running normally on your local? Or does Valve not support this login method?

**Comment by jackzuan** [comment]
Fixed the issue. Due to bind host #23.196.199.170 steamcommunity.com.
But show another issue bug, 
![image](https://github.com/fnyah/Steam-Login-Express/assets/1006029/19a30560-8a75-4876-b414-c91f6438f29f)
InternalOpenIDError: Failed to verify assertion

**Comment by fnyah** [comment]
I had that error when I put in my steam API key incorrectly.

**Comment by fnyah** [comment]
Gonna mark this as closed, if you have any other questions don't hesitate to reach out.
